### ISSUE TITLE
ang2pix, pix2ang

### ISSUE THREAD

**Issue by cdeil** [pmplewa/HealPix.js#1]
Hi, I'm looking for a JS library to do HEALPix ang2pix, pix2ang.

Would you be interested to add this here, or accept a contribution?
E.g. translating https://github.com/ziotom78/Healpix.jl to JS should be pretty straightforward.

There is https://github.com/kapadia/healpix.js but that's pretty heavy and GPL.

**Comment by pmplewa** [comment]
Hi Christoph, sorry for the late reply, I missed the notification.

The conversion functions `ang2XY` and `XY2ang` that I implemented use pixel indices in the XY scheme, which is explained [here](https://github.com/dstndstn/astrometry.net/blob/master/include/astrometry/healpix.h). Determining the corresponding indices in the standard RING or NESTED schemes should be possible by translating the functions `healpix_xy_to_ring`, `healpix_ring_to_xy`, `healpix_xy_to_nested` and `healpix_nested_to_xy` from [this C code](https://github.com/dstndstn/astrometry.net/blob/master/util/healpix.c).

Which indexing scheme are you planning to use? If you are still interested, I would be happy to take a closer look at these functions.

**Comment by cdeil** [comment]
@pmplewa - Thanks for the reply!

In the meantime I found https://github.com/michitaro/healpix/ . It turns out that I don't have a real use for JS at the moment, so please disregard this feature request from me.
